name: Fofa Scraper

on:
  schedule:
    # 每6小时执行一次任务
    - cron: '0 */6 * * *'  # 每 6 小时执行一次，使用 UTC 时间
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  scrape:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的虚拟环境

    steps:
    # 第一步：检出代码
    - name: Check out repository
      uses: actions/checkout@v3

    # 第二步：设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 设置 Node.js 版本（根据需要调整）

    # 第三步：安装依赖
    - name: Install dependencies
      run: npm install

    # 第四步：运行抓取脚本
    - name: Run scraper script
      run: node scrape.js

    # 第五步：上传抓取结果（iptv.txt 和 iptvdl.txt）为工作流工件
    - name: Upload scrape results
      uses: actions/upload-artifact@v3
      with:
        name: fofa-scrape-results
        path: |
          iptv.txt
          iptvdl.txt
