name: Scrape FOFA Pages

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次（UTC 时间）
  workflow_dispatch:        # 支持手动触发运行

jobs:
  scrape:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 服务器运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 使用 actions/checkout@v4 版本

      - name: Setup Node.js
        uses: actions/setup-node@v4  # 使用 actions/setup-node@v4 版本
        with:
          node-version: '20'       # 安装 Node.js 20 版本

      - name: Install dependencies
        run: npm install           # 安装 puppeteer 等依赖项

      - name: Run scraper
        run: npm start             # 执行爬虫脚本 scrape.js

      - name: Upload output HTML files
        uses: actions/upload-artifact@v4  # 使用 actions/upload-artifact@v4 版本
        with:
          name: fofa-html
          path: |
            iptv.html
            iptvdl.html
